# Makefile for CSE 13S, Spring 2023, Assignment 5

# DO NOT EDIT THIS FILE

# Usage:
#
#    $ make             Make the sorting program (ready for LLDB debugging).
#    $ make all
#
#    $ make clean       Type this command after editing this Makefile or
#                       when switching between all and release targets.
#
#    $ make format      Run clang-format on *.c and *.h
#
#    $ make release     Make the sorting program (without debugging info).
#                       We use this for the reference design.


CC     = clang
CFLAGS = -Wall -Wextra -Werror -Wstrict-prototypes -pedantic
LFLAGS = -lm
EXEC   = colorb
colorb_OBJS   = colorb.o io.o bmp.o
iotest_OBJS   = io.o iotest.o

all: colorb iotest

colorb: $(colorb_OBJS)
	$(CC) $(LFLAGS) -o colorb $(colorb_OBJS)

iotest: $(iotest_OBJS)
	$(CC) $(LFLAGS) -o iotest $(iotest_OBJS)

%.o: %.c
	$(CC) $(CFLAGS) -c $<

clean:
	rm -f colorb iotest $(colorb_OBJS) $(iotest_OBJS)

format:
	clang-format -i --style=file *.[ch]

scan-build: clean
	scan-build --use-cc=$(CC) make

